### ISSUE TITLE
NASA Champions followup

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/how_we_work#44]
Some TODOs as followup:

- [x] Call 5 Digest - @jules32 
- [x] Blog summary @erinmr 
- [x] Add songs to spotify
- [x] Write cards & stickers - @erinmr do you want to start them?
- [ ] ~scheduling 1:1s - create spreadsheet & reach out - @jules32 can follow up after we start together~

**Comment by erinmr** [comment]
@jules32 - I can start the cards/stickers and the blog summary

**Comment by erinmr** [comment]
Let's collect addresses when we meet with the teams 1-1

**Comment by jules32** [comment]
We'll send the digest on Thursday after we discuss with the Mentors

**Comment by erinmr** [comment]
@jules32 - here is a [draft blog](https://docs.google.com/document/d/1C4rrQ27wTPAKmAFJyRJEsa-6fvzGRe5Nnjhw6tct4BI/edit#)
