### ISSUE TITLE
Test Calendar OpenscapesCoworking to coordinate hacktimes

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/how_we_work#51]
Hi All, 

**We’re creating a hopefully light-weight system for calendaring hacktimes** 

Goal is to meet the following needs:

- Mentors can see all NASA Openscapes coworking/hackdays going on
- Mentors can all create new coworking/hackday events
- Updates are visible across different calendars (Google/Outlook/etc)
- Mentors can add zoom/Teams/Google Meet info as needed (not centralized, not limited to Stef/Julie availability)
- Would like to ultimately share publicly, need to experiment with how we want to share call in info publicly (learn from Carpentries/CSCCE on this)

**Please test the following and respond in a comment / with screenshots if** 

1. Did you get email that you’re in the new Google Group `nasa-openscapes-mentors`?
2. Did you get email to access OpenscapesCoworking Google Calendar subject: ‘Stefanie Butland has shared a calendar with you’? 
3. Can you see the Feb 6 earthaccess hackday invite on your Calendar? 
4. Please share a screenshot of what it looks like in your Calendar? 
5. ~Add an event and invite stefanie@openscapes.org~
6. (edited Jan 29) Add an event to the OpenscapesCoworking Google Calendar and invite the Google Group as a guest: `nasa-openscapes-mentors@openscapes.org`

**Comment by jules32** [comment]
Hi @stefaniebutland ! 

1. yes, received
2. yes!
3. yes
4. screenshot - yes I see earthaccess

![Image](https://github.com/NASA-Openscapes/how_we_work/assets/5891909/320c9eb5-f752-4c8d-b4f9-05aa726403a7)

5. screenshot - this is how I added the Google Group. And you can see it also shows up as an invite in the screenshot above too!
![Image](https://github.com/NASA-Openscapes/how_we_work/assets/5891909/12a7b4c7-91ae-4e64-88b1-76a346362e4b)

**Comment by danielfromearth** [comment]
1. Yes
2. No, I don't see this particular email subject
3. Yes, with a subject "[EXTERNAL] Updated invitation: earthaccess hackdays, biweekly @ Tue Feb 6, 2024 10am - 12pm (PST)"
4. 
<img width="1083" alt="snapshot" src="https://github.com/NASA-Openscapes/how_we_work/assets/114174502/cb1dd9a0-a221-4a87-9232-d79591847423">
5. Done
6. Done

**Comment by BriannaLind** [comment]
1. yes
2. no
3. no
4. no 
5. no

I did get an invite from Danny though!

**Comment by stefaniebutland** [comment]
@danielfromearth thanks for testing. 
Helped me realize **I need to me clearer in my instructions**. The idea is instead of creating an item in your personal calendar and inviting `nasa-openscapes-mentors@openscapes.org`, you create it in the OpenscapesCoworking Calendar and invite. I wonder if it's clear/ straightforward to do in Outlook (I think that's what you're using). Screenshot below shows what it looks like for me using Google Calendar.

Would you mind trying this?

![Screenshot 2024-01-29 at 11 17 26 AM](https://github.com/NASA-Openscapes/how_we_work/assets/11927811/d3a414ec-fbb8-4fb1-9b64-4fa7f8a0dfb4)


## From your testing
(not critical; adding here for the record)
I received 2 emails. One for invite to stefanie@openscapes.og; One for invite to `nasa-openscapes-mentors@openscapes.org`. The latter did not automatically appear in my calendar. Email with invite to `nasa-openscapes-mentors@openscapes.org` offered 'Add to calendar' (screenshot). 

![Screenshot 2024-01-29 at 11 09 12 AM](https://github.com/NASA-Openscapes/how_we_work/assets/11927811/602eba54-23ec-40c0-917e-2bd4a72f4a62)

**Comment by stefaniebutland** [comment]
@BriannaLind Thanks for testing! do you have time to troubleshoot with me in zoom? It will help me to see what you're seeing. I'll DM you a link to book time.

**Comment by stefaniebutland** [comment]
Bri saw this awesome calendar page https://scientific-python.org/calendars/

**Comment by BriannaLind** [comment]
I only got this email group google groups 
![image](https://github.com/NASA-Openscapes/how_we_work/assets/104585874/84e4642c-4a5a-4a16-9a8c-07e740006219)

**Comment by stefaniebutland** [comment]
Troubleshooting with @BriannaLind 

Screenshot of Jan 25 email (from Google?) giving Mentors access to OpenscapesCoworking calendar
![Screenshot 2024-01-30 at 8 40 57 AM](https://github.com/NASA-Openscapes/how_we_work/assets/11927811/9b7fc246-76e7-4226-b4d5-5229abce7549)

**Comment by BriannaLind** [comment]
![image](https://github.com/NASA-Openscapes/how_we_work/assets/104585874/32d24c9b-7f27-4142-97ab-17b8eed48901)
https://support.google.com/groups/answer/1067205?hl=en#:~:text=Some%20groups%20let%20you%20join,for%20a%20child%20under%2013.

**Comment by stefaniebutland** [comment]
Outcome: looks like Bri and others can't contribute to a google group calendar without using their gmail. Does not make sense to ask folks to do that.

Stef will ask in CSCCE Slack for solutions

**Comment by asteiker** [comment]
@stefaniebutland It looks like you've been making progress here but if my troubleshooting helps further:

- [ ] Did you get email that you’re in the new Google Group nasa-openscapes-mentors? YES, but when I click "View this Group" i get a 403.
- [ ] Did you get email to access OpenscapesCoworking Google Calendar subject: ‘Stefanie Butland has shared a calendar with you’? NO
- [ ] Can you see the Feb 6 earthaccess hackday invite on your Calendar? YES but I think it only has Luis and myself on as invitees in my Outlook.
- [ ] Please share a screenshot of what it looks like in your Calendar? See below. Different invitees in my Outlook (which is what I use) vs what it's my Google calendar.
- [ ] Add an event to the OpenscapesCoworking Google Calendar and invite the Google Group as a guest: nasa-openscapes-mentors@openscapes.org - I just did this for Wed 31st at 8 MT
![Screenshot 2024-01-30 at 10 34 46 AM](https://github.com/NASA-Openscapes/how_we_work/assets/47193922/e6194471-3a06-45c1-aaac-5e45c77da8b4)
![Screenshot 2024-01-30 at 10 35 04 AM](https://github.com/NASA-Openscapes/how_we_work/assets/47193922/d85bda5d-2dc5-4637-ab39-3cc062c13d4f)

**Comment by stefaniebutland** [comment]
Thank you @asteiker ! so helpful.
I see your  Wed 31st at 8 MT invite; looks like this:

![Image](https://github.com/NASA-Openscapes/how_we_work/assets/11927811/bff5e395-c372-4078-bf6b-b07e5914a50e)


@BriannaLind do you see the Wed 31st at 8 MT invite Amy created above?

**Comment by stefaniebutland** [comment]
Sought advice in [CSCCE](https://www.cscce.org/) Slack

@ha0ye suggested the [delegation method](https://support.google.com/a/users/answer/170961?sjid=16958651209457380843-NA) might work for mentors using outlook.   
From Google [set up delegation](https://support.google.com/a/users/answer/170961?sjid=16958651209457380843-NA):
> Google Workspace Sync for Microsoft Outlook. If you use Google Workspace Sync for Microsoft Outlook (GWSMO), you can manage another person's Gmail or Google Calendar (such as your manager) from Outlook. Make sure the other person has granted you access to their Gmail account and Calendar. For details, go to [Delegate access to your mail or calendar](https://support.google.com/a/users/answer/170957).
🤔 To implement, we'd want to set up a new Openscapes Google Workspace account for this since we don't want to give access to our personal work accounts, but multi-person access might not be possible

Brittany Aguilar suggested Airtable. Create a base, use a tab for “calendar events”, and set up a mini extension form for event submissions. You can add a login to the form so only certain people can submit. 
- We don't currently use Airtable. Free version allows up to 5 editors and we'd need 40 editors

I looked at/tested adding event to https://openresearchcalendar.org/ since source is on GitHub. But adding new event is a different workflow cf Google cal so we don't want to introduce YAW (yet another workflow).

## Conclusion
**This works:** NASA Mentors can create a calendar event from their system of choice, and invite `nasa-openscapes-mentors at openscapes.org` as guest. Mentors in that Google Group will get the invitation. If they say 'yes' to invite, it will show in their calendar. This does not involve using the OpenscapesCoworking Google calendar.

**The missing piece is**  that people can't see in their calendar the events they decline to attend. That's a problem for scheduling other sessions.

**Comment by jules32** [comment]
Closing for now

**Comment by jules32** [comment]
Several Mentors have reported no longer having Wednesday calendar invites on their calendars. 

Today I: 

- tested calendars showing up by creating a test-jul2-2024 Google Group and adding calendar items
- deleted Wednesday Mentor calendar invites going forward
- recreated and invited Wednesday Mentor calendar invites for the nasa-openscapes-mentors@openscapes group
