### ISSUE TITLE
ESIP Session - Fledging - July 23

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/how_we_work#61]
**ESIP summer meeting is July 22-26 in Asheville, North Carolina.** 

**Theme this year:  Grounded in Trust: Data Ethics Empower Collaboration.** 

## Session information - updated May 31

**[draft session schedule](https://docs.google.com/spreadsheets/d/1XXNk1oHm6z02t9V_zVZCtWtXQlHLIu205UzHzGp6n2w/edit#gid=1190381363)**

[**Sched site**](https://2024julyesipmeeting.sched.com/event/1eNkr/supporting-nasa-earthdata-users-in-the-cloud-nasa-openscapes-onboarding-and-fledging) - tentative time: Tuesday July 23 2-3:30pm ET. Note Julie has asked ESIP team to update name to all co-leads.

## Submission Planning - May 1

[Call for Sessions Google Doc](https://docs.google.com/document/d/1uP4VXsVLQB1Ihk2nGXAqsaQoRNMzGzjRXv4lTw4GMyE/edit) - includes: 

[Google Submission Form](https://docs.google.com/forms/d/e/1FAIpQLSeJOVKUiL7Xl69v9IAZGrckqe-c_k3znGRhoHY5lHWQRRmk-w/viewform)
[Google Submitted Responses Sheet](https://docs.google.com/spreadsheets/d/1zD9iTljfnOVGPpg-PMjaRul79zKYVgbhp9kQctNSvHA/edit#gid=454453861)

## NASA Openscapes session - fledging

Starting plan: Status and vision of earthaccess / Cookbook / hub inrastructure /workshop planning >> “fledging”. Would be great to share and get feedback and connect

[draft session proposal](https://docs.google.com/document/d/12o_lv6oYN9wNUIWGD0Eff2ldQccrpPUibXN_UAO36ko/edit)

**Comment by jules32** [comment]
Worked on the draft proposal more today and tagged in person folks on Slack

**Comment by jules32** [comment]
Submitted!

**Comment by jules32** [comment]
Hello Session Organizers, 

Thanks again for your contributions and ideas! We look forward to seeing you in Asheville in July.

We are double checking the ESIP Meeting agenda for time/speaker conflicts and next Tuesday, May 28 we will send a draft schedule for you to review. Please block off time next Tuesday or Wednesday to look over the schedule and let us know about any issues. (Or let me know if you will be out next week and we will make separate arrangements.)

The ESIP team will finalize the agenda in the [2024 July ESIP Meeting - Sched site](https://2024julyesipmeeting.sched.com/) by noon ET on Friday, May 31. 

Even with running five concurrent sessions, we received more sessions than can physically fit into the schedule. We will be reaching out to a handful of session organizers this afternoon to combine sessions. If you don't hear from us, assume you will have a 90-minute session block.

And if you haven't already, make sure to sign up for the [Session Design Workshop](https://www.esipfed.org/event/jul24-session-design-workshop/) on June 12 with our facilitator Charley Haley!

Enjoy the long weekend.

- Allison

**Comment by jules32** [comment]
Included Yuvi Panda when we start planning; he may be in person as well

**Comment by alexishunzinger** [comment]
@alexishunzinger, @michele-ornl, and @danielfromearth met during coworking today (6/20) to start brainstorming/drafting a session agenda. See the [table in the ESIP_Summer2024 planning](https://docs.google.com/document/d/12o_lv6oYN9wNUIWGD0Eff2ldQccrpPUibXN_UAO36ko/edit#bookmark=id.9h19qyzctmcf) doc.

We should plan to meet again soon (next coworking? next cohort call?) to finalize and also reach out to possible speakers

**Comment by jules32** [comment]
This is great @alexishunzinger et al! Yes let's have time for this Wednesday (6/26) during the Mentor Call.

**Comment by jules32** [comment]
Notes from ESIP with July 8 deadlines for Sched and requests; also ESIP template slide deck - 


**Open Office Hour This Week:** On Wednesday, join Charley Haley from Way Foragers for an [Open Office Hour](https://www.esipfed.org/event/open-office-hour-with-charley-haley/2024-06-26/). Join via the ESIP Community Calendar (2 PM ET). The [next Open Office Hour](https://www.esipfed.org/event/open-office-hour-with-charley-haley/2024-07-01/) is Monday, July 1 at 3 PM ET. You can also [request a 1:1 consultation](https://calendly.com/charleyhaley) with Charley via her Calendly. 

**ESIP Office Closed:** In honor of the July Fourth holiday, ESIP is closed next Thursday (and most of us will be out Friday, July 5!)

**July 8 Deadline for Sched:** From edits to Slido to paper and pens, make sure to plan ahead and get all your session materials ready to go. 

-   **Update your session descriptions.** Add talk abstracts, resources, agenda, and anything else to help recruit and prepare attendees for your session. Add all info by July 8. After that, you will need to email [staff\@esipfed.org](mailto:staff@esipfed.org) to request edits. 

-   **Send lists of speakers to [staff\@esipfed.org](mailto:staff@esipfed.org)** Once a speaker has registered, then ESIP staff can tag the account as a speaker and add them to your session. You will be unable to make these edits on your own and we cannot add speakers until the person has registered.

-   **Slido is a great collaborative tool.** It streamlines and documents Q&A and features many other tools like polling, word clouds, open text, and more. Email [staff\@esipfed.org](mailto:staff@esipfed.org) to request a Slido link for your session and to be added as a collaborator so you can access the admin interface.

-   **Nothing quite like analog.** Did you know writing with a pen activates a different part of the brain than typing and texting? Neat! And for reflective or creative activities, sometimes there is no replacement for flipcharts, markers, stickers, etc. But we can't magically make those materials appear, so send [staff\@esipfed.org](mailto:staff@esipfed.org) a request if you need them.

-   **Other questions?** You guessed it, send them to [staff\@esipfed.org](mailto:staff@esipfed.org) and we will help. 

**Time Savers (and Keepers):** Staying on time and on track during a session takes effort — and a little planning goes a long way. Here are some tools and tips to help.

-   **Storyboard:** Charley Haley offered a [generic storyboard](https://docs.google.com/document/d/16p4-7l1XhIfOC2OstjXsgQt9gHTQixEi/edit?usp=sharing&ouid=118425071811894325242&rtpof=true&sd=true) and a [soil data semantics example](https://docs.google.com/document/d/1zIZN0ic-e7tLmKPTPe3Csf8C6X2GLhGf/edit?usp=sharing&ouid=118425071811894325242&rtpof=true&sd=true) 

-   **Talk to your speakers:** Be very clear about your expectations with speakers; see our speaker guidance on page 1-2 of the [session guidance doc](https://www.esipfed.org/jul24-session-guidance). 

-   **Help your speakers out.** Most of us overdo slides and presentations in an effort to be helpful and insightful. But this can lead an audience to information overload. Tell your speakers specific time limits -- and offer them prompts or tell them your goals for their presentations so they can focus their materials.

-   **Slide Templates:** As we've learned through [Ignite\@AGU](https://igniteagu.io/), some of our most creative talks come from working inside strict parameters. Consider giving your speakers a set of slides with prompts or offer them the [**ESIP slide deck**](https://www.esipfed.org/jul24-slides-template).

-   **Keeping Time:** Save yourself from the awkward interruption and wielding the shepherd's crook to pull someone away from the podium. Come up with a subtle way to communicate time limits to your speakers. Tools we've seen: setting a phone with a stopwatch running on the podium, birdsong or nature sounds for alarms, color-coded cards, hand signals, and moderator quietly rising to stand in the back.

**Comment by jules32** [comment]
Danny & I attended ESIP Office Hours yesterday with Charley Haley, Allison Mills, Megan Orlando: really helpful for our session design! We have a draft agenda with design notes in our [Planning Doc](https://docs.google.com/document/d/12o_lv6oYN9wNUIWGD0Eff2ldQccrpPUibXN_UAO36ko/edit#bookmark=id.18ueqwwv6ubt). 

Next steps: huddle together to confirm agenda plan and create the slide deck!

**Comment by jules32** [comment]
Today Alexis, Aaron, Danny & I discussed the [Planning Doc](https://docs.google.com/document/d/12o_lv6oYN9wNUIWGD0Eff2ldQccrpPUibXN_UAO36ko/edit#bookmark=id.18ueqwwv6ubt) further, and added details for presenters and started a [Slide Deck](https://docs.google.com/presentation/d/1-TiPN8bfY6iDL5EVcEuCQSjqFMs3jPSX2MlNWA6no2E/edit#slide=id.g2eae202a90f_4_248). We'll continue working on it tomorrow in Coworking and on Wednesday in Mentors' Call, then figure out how much async vs coworking from there!

I requested 5x sticky poster boards and pens and updated [our Sched ](https://2024julyesipmeeting.sched.com/event/1eVNz/mt-pisgah-supporting-nasa-earthdata-users-in-the-cloud-nasa-openscapes-onboarding-and-fledging) with our current POP and requested that Aaron is added.

**Comment by jules32** [comment]
Tagging @amfriesz here too :)

**Comment by jules32** [comment]
Today I've emailed [staff@esipfed.org](mailto:staff@esipfed.org) to request a Slido link for our session and to be added as a collaborator so we can access the admin interface.

**Comment by jules32** [comment]
Hi All! 

Let's plan to cowork on slides during Coworking Thursday 10-11:30PT. Please Slack if you're working on them beforehand and we can work asyncronously. 

**Monday night Happy Hour: at the Green Man Brewery** If you're in town Monday evening, let's do happy hour! How about 5pm? 
https://www.greenmanbrewery.com/
27 Buxton Ave, Asheville, NC 28801

It's an 9 min drive from the Crowne Plaza, we can carpool by meeting in the lobby at 4:45

**Comment by jules32** [comment]
Hi @alexishunzinger, I reviewed Aronne Merelli's talk and made 2 slides in the [ESIP slide deck](https://docs.google.com/presentation/d/1-TiPN8bfY6iDL5EVcEuCQSjqFMs3jPSX2MlNWA6no2E/edit#slide=id.g2eae202a90f_4_248) that could be a good way to share his story; just a start and excited to see what you think/where you take it!

**Comment by alexishunzinger** [comment]
Thank you @jules32! I just got back into office-world today and need to prepare more for the session and presentation. Will be in coworking tomorrow.

**Comment by jules32** [comment]
Hi All, We'll be finalizing agenda, slides, slido questions asynchronously in the next few days, and planning to meet 7:30-9pm Monday in the Hotel Lobby if you're able to make it!

**Comment by jules32** [comment]
@alexishunzinger and I huddled during coworking today to start a summary blog post; I'll work more on the opening text and she and Chris will look through the participant sticky notes (pictures in the breakout slides). We'll share with coauthors for edits/approval and then post later in August when it's done

**Comment by jules32** [comment]
@alexishunzinger I finished the draft post from my side - do you want to add any insights from the sticky notes/your poster and then we can share with others for feedback/approval?

It was fun reviewing all of this, great work everyone ❤

**Comment by alexishunzinger** [comment]
@jules32 Thanks for drafting  - and nudging! I just read thru and made minor edits, and finishing putting insights into those bullets now.

**Comment by jules32** [comment]
Closing this since we've got blog posts posted, and are planning our AGU talk (linked issue just above). 

Blogs: 

https://www.earthdata.nasa.gov/learn/blog/onboarding-fledging-and-beyond-openscapes-journey - Josh Blumenfeld
https://nasa-openscapes.github.io/news/2024-08-30-esip-summer-2024/

**Comment by jules32** [comment]
Great catch, I've asked!
